version: "3.8"

x-backend-templates:
  app: &backend-template
    image: matheuslferreira/paymentgateway:latest
    environment:
      QUEUE_BUFFER: 9000
      LOG_LEVEL: off
      SERVER_PORT: 8080
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
      JAVA_OPTS: >-
        -Xms32m -Xmx96m
        -XX:MaxMetaspaceSize=40m
        -Dio.netty.maxDirectMemory=12m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=50
        -XX:+AlwaysActAsServerClassMachine
        -Xlog:disable
    networks: [backend, payment-processor]
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "135MB"

services:
  load-balancer:
    image: nginx:alpine
    container_name: nginx-rinha
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: [ "9999:80" ]
    networks: [backend]
    depends_on: [ backend-1, backend-2 ]
    deploy:
      resources:
        limits:
          cpus: "0.18"
          memory: "45MB"

  backend-1:
    <<: *backend-template
    container_name: backend-1
    hostname: backend-1

  backend-2:
    <<: *backend-template
    container_name: backend-2
    hostname: backend-2

networks:
  backend: { driver: bridge }
  payment-processor: { external: true }

