version: '3.8'

services:
  # Nginx Load Balancer
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  # API Instance 1
  api1: &api
    image: wallacemendes/rinha-backend-2025-node:latest
    hostname: api1
    container_name: rinha-api1
    environment:
      - NODE_ENV=production
      - API_PORT=8080
      - API_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_HOST=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_HOST=http://payment-processor-fallback:8080
      - ENABLE_WORKER=true
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rinha-network
      - payment-processor
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

  # API Instance 2
  api2:
    <<: *api
    hostname: api2
    container_name: rinha-api2
    environment:
      - NODE_ENV=production
      - API_PORT=8080
      - API_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_HOST=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_HOST=http://payment-processor-fallback:8080
      - ENABLE_WORKER=true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: ["redis-server", "--appendonly", "no", "--appendfsync", "no", "--save", "", "--maxclients", "20000", "--maxmemory", "55mb"]
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true