x-backend-templates:
  app: &app
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    image: csouzadocker/rinha-2025-redis:latest
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

  app-env: &app-env
    SERVER_PORT: "8080"
    THREAD_POOL_SIZE: "25"
    THREAD_QUEUE_SIZE: "5000"
    REDIS-HOST: "redis"
    REQUEST_CONNECTION_TIMEOUT: "100"
    REQUEST_READ_TIMEOUT: "1500"
    payment-processor.default.url: "http://payment-processor-default:8080"
    payment-processor.fallback.url: "http://payment-processor-fallback:8080"
    JAVA_OPTS: "\
    -Xmx110m \
    -Xms110m \
    -XX:MaxMetaspaceSize=70m \
    -XX:+UseSerialGC \ \
    -XX:+UseNUMA \
    -Xss512k \
    -XX:+UseCompressedOops \
    -XX:+AlwaysPreTouch \
    -Xbatch \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -XX:CompileThreshold=100
    -XX:+HeapDumpOnOutOfMemoryError \
    -Dlogging.level.root=warn \
    -Dspring.threads.virtual.enabled=false \
    -Dserver.undertow.threads.io=4 \
    -Dserver.undertow.threads.worker=5"
#    -XX:+UnlockDiagnosticVMOptions \
#    -XX:+PrintCompilation \
#    -XX:+PrintTieredEvents \
#    -XX:+PrintCodeCache \
#    -XX:+PrintInlining"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

  app1:
    <<: *app
    container_name: backend-api1
    hostname: app1
    environment:
      <<: *app-env

  app2:
    <<: *app
    container_name: backend-api2
    hostname: app2
    environment:
      <<: *app-env

  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save "" --tcp-keepalive 60 --timeout 0
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "55MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
