services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-1:1.0.0
    environment:
      RETRY_API_DEFAULT: 16
      WORKER_POOL_SIZE: 25
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080/payments
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080/payments
      LOG_LEVEL: off
      SERVER_PORT: 8080
      BACK_END_URL: http://backend-2:8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.625'
          memory: '140MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-1:1.0.0
    restart: always
    environment:
      RETRY_API_DEFAULT: 16
      WORKER_POOL_SIZE: 25
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080/payments
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080/payments
      LOG_LEVEL: off
      SERVER_PORT: 8080
      BACK_END_URL: http://backend-1:8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.625'
          memory: '140MB'

  load-balancer:
    image: nginx:alpine
    restart: always
    container_name: gabxdev-load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true