version: "3.9"

networks:
  default:
    external: true
    name: payment-processor

services:
  lb:
    image: nginx:alpine
    container_name: lb
    ports:
      - "9999:9999"
    command: ["sh", "-c", "echo 'events { worker_connections 1024; } http { access_log off; upstream api { server api01:8080; server api02:8080; } upstream worker { server worker:8081; } server { listen 9999; location /payments-summary { proxy_pass http://worker; } location / { proxy_pass http://api; } } }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api01:
    image: quay.io/rhn_support_arolivei/rinha-de-backend-2025-golang:latest
    environment:
      - WORKER_HOST=worker
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres:5432/rinha?sslmode=disable
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  api02:
    image: quay.io/rhn_support_arolivei/rinha-de-backend-2025-golang:latest
    environment:
      - WORKER_HOST=worker
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres:5432/rinha?sslmode=disable
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  worker:
    image: quay.io/rhn_support_arolivei/rinha-de-backend-2025-golang:latest
    ports:
      - "8081:8081"
    environment:
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - POSTGRES_DSN=postgresql://postgres:postgres@postgres:5432/rinha?sslmode=disable
      - MODE=worker
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "80MB" 
