services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java:2.0.1
    container_name: gaxdev-backend-1
    environment:
      RETRY_API_DEFAULT: 14
      WORKER_POOL_SIZE: 21
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080/payments
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080/payments
      LOG_LEVEL: off
      BACK_END_URL: http://backend-2:8080
      SERVER_PORT: 8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.61'
          memory: '120MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java:2.0.1
    container_name: gaxdev-backend-2
    restart: always
    environment:
      RETRY_API_DEFAULT: 14
      WORKER_POOL_SIZE: 21
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080/payments
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080/payments
      LOG_LEVEL: off
      BACK_END_URL: http://backend-1:8080
      SERVER_PORT: 8080
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.61'
          memory: '120MB'

  load-balancer:
    image: gabxdevv/loud-balance-diferenciado:1.0.2
    restart: always
    container_name: gabxdev-load-balance-bolado
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.28"
          memory: "110MB"
    environment:
      BACK_END_1_URL: ws://backend-1:8080/backend
      BACK_END_2_URL: ws://backend-2:8080/backend
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true