DROP TABLE IF EXISTS payments;

CREATE TABLE payments (
    correlation_id VARCHAR(150) PRIMARY KEY NOT NULL UNIQUE,
    amount DOUBLE PRECISION NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    provider VARCHAR(10) NOT NULL
);