services:
  app1:
    image: willrodrigues/agorinha-2025:latest
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - QUEUE_SIZE=10000
      - WORKERS=8
      - STORE_JSON_PATH=/data/store.json
      - STORE_LOCK_PATH=/data/store.lock
    networks:
      - backend
      - payment-processor
    volumes:
      - rinha-store:/data
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

  app2:
    image: willrodrigues/agorinha-2025:latest
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - QUEUE_SIZE=10000
      - WORKERS=8
      - STORE_JSON_PATH=/data/store.json
      - STORE_LOCK_PATH=/data/store.lock
    networks:
      - backend
      - payment-processor
    volumes:
      - rinha-store:/data
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "140MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  rinha-store:
