@port = 8001
@token = 123


GET http://localhost:{{port}}/payments/service-health

###

POST http://localhost:9999/payments
Content-Type: application/json

{
    "correlationId": "{{$guid}}",
    "amount": 19.90
}

###

GET http://localhost:9999/payments-summary 
//?from=2025-07-04T00:16:15.912&to=2025-07-04T00:17:15.690

### 
GET http://localhost:8001/admin/payments-summary?from=2000-01-01T00:00:00&to=2100-01-01T00:00:00
//?from=2025-07-04T00:16:15.912&to=2025-07-04T00:17:15.690
X-Rinha-Token: {{token}}

### 
GET http://localhost:8002/admin/payments-summary
//?from=2025-07-04T00:16:15.912&to=2025-07-04T00:17:15.690
X-Rinha-Token: {{token}}


###

PUT http://localhost:{{port}}/admin/configurations/delay
X-Rinha-Token: {{token}}
Content-Type: application/json

{
    "delay": 0
}

###

PUT http://localhost:{{port}}/admin/configurations/failure
X-Rinha-Token: {{token}}
Content-Type: application/json

{
    "failure": false
}

###

PUT http://localhost:{{port}}/admin/configurations/fee
X-Rinha-Token: {{token}}
Content-Type: application/json

{
    "fee": 2.0
}

###

GET http://localhost:{{port}}/admin/payments-summary
X-Rinha-Token: {{token}}

###

POST http://localhost:{{port}}/admin/purge-payments
X-Rinha-Token: {{token}}
